package com.v1.acro.uiscreens

import android.Manifest
import android.content.Context
import android.content.pm.PackageManager
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.ContextCompat
import androidx.core.content.FileProvider
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavController
import coil.compose.AsyncImage
import com.v1.acro.ui.theme.*
import com.v1.acro.viewmodel.ProductViewModel
import java.io.File

/**
 * ============================================================
 * AddProduct.kt
 * ============================================================
 *
 * Form screen to add new products to inventory.
 *
 * STRUCTURE:
 *   AddProduct (entry point)
 *     ├── ImagePicker     → camera capture for product photo
 *     ├── BarcodeScanner  → ML Kit barcode scan (auto-fills fields)
 *     ├── ProductForm     → name, price, quantity inputs
 *     └── SaveButton      → commits to Room DB via ViewModel
 *
 * DATA:
 *   - Product ID is auto-generated by Room (@PrimaryKey autoGenerate)
 *   - Save inserts via ProductViewModel.addProduct()
 *
 * UPDATE NOTE:
 *   - ImagePicker camera capture is wired (CameraX TakePicture + FileProvider);
 *     the captured photo Uri is saved to the product and shown via Coil AsyncImage.
 *     Requires the FileProvider in AndroidManifest + res/xml/file_paths.xml.
 *   - Barcode scanner auto-fills productBarcode (see SharedComponents.BarcodeScannerButton).
 *   - Both camera features request the CAMERA runtime permission on demand.
 *
 * TODO:
 *   - Add input validation feedback (currently silent on invalid)
 *
 * NAVIGATION:
 *   Route: "AddProduct"
 *   Entry: HomeScreen TaskCard → navController.navigate("AddProduct")
 * ============================================================
 */

@Composable
fun AddProduct(
    navController: NavController,
    viewModel: ProductViewModel = viewModel()
) {
    var productName by remember { mutableStateOf("") }
    var productPrice by remember { mutableStateOf("") }
    var productQuantity by remember { mutableStateOf("") }
    var productImageUri by remember { mutableStateOf<String?>(null) }
    var productBarcode by remember { mutableStateOf<String?>(null) }

    // Error states
    var priceError by remember { mutableStateOf(false) }
    var quantityError by remember { mutableStateOf(false) }

    // Camera capture for the product photo
    val context = LocalContext.current
    var pendingImageUri by remember { mutableStateOf<Uri?>(null) }

    val takePictureLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.TakePicture()
    ) { success ->
        if (success) productImageUri = pendingImageUri?.toString()
    }

    fun launchCamera() {
        val uri = createProductImageUri(context)
        pendingImageUri = uri
        takePictureLauncher.launch(uri)
    }

    val cameraPermissionLauncher = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission()
    ) { granted -> if (granted) launchCamera() }

    val onCapture = {
        val hasPermission = ContextCompat.checkSelfPermission(
            context, Manifest.permission.CAMERA
        ) == PackageManager.PERMISSION_GRANTED
        if (hasPermission) launchCamera()
        else cameraPermissionLauncher.launch(Manifest.permission.CAMERA)
    }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(16.dp)
            .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text(
            text = "Add New Product",
            fontSize = 20.sp,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )

        ImagePicker(
            imageUri = productImageUri,
            onCaptureClick = onCapture
        )

        BarcodeScannerButton(onBarcodeScanned = { scannedValue -> productBarcode = scannedValue })

        ProductFormField(
            label = "Product Name",
            value = productName,
            onValueChange = { productName = it },
            placeholder = "e.g. Indomie Goreng"
        )

        // Price field with formatting and validation
        ProductNumberField(
            label = "Price",
            value = productPrice,
            onValueChange = {
                productPrice = it
                priceError = false
            },
            placeholder = "e.g. 3.500",
            isError = priceError,
            errorMessage = "Price can only contain numbers"
        )

        // Quantity field with formatting and validation
        ProductNumberField(
            label = "Quantity",
            value = productQuantity,
            onValueChange = {
                productQuantity = it
                quantityError = false
            },
            placeholder = "e.g. 50",
            isError = quantityError,
            errorMessage = "Quantity can only contain numbers"
        )

        Spacer(modifier = Modifier.height(8.dp))

        SaveButton(
            onClick = {
                // Strip dots before parsing (2.000 → 2000)
                val rawPrice = productPrice.replace(".", "")
                val rawQuantity = productQuantity.replace(".", "")

                val price = rawPrice.toDoubleOrNull()
                val quantity = rawQuantity.toIntOrNull()

                // Set errors
                priceError = price == null && productPrice.isNotBlank()
                quantityError = quantity == null && productQuantity.isNotBlank()

                if (productName.isNotBlank() && price != null && quantity != null) {
                    viewModel.addProduct(
                        name = productName,
                        price = price,
                        quantity = quantity,
                        imageUri = productImageUri,
                        barcode = productBarcode
                    )
                    navController.popBackStack()
                }
            }
        )
    }
}

/**
 * Creates a FileProvider Uri for a new product photo under filesDir/images/.
 * The camera writes the captured image to this Uri.
 */
private fun createProductImageUri(context: Context): Uri {
    val imagesDir = File(context.filesDir, "images").apply { mkdirs() }
    val file = File(imagesDir, "product_${System.currentTimeMillis()}.jpg")
    return FileProvider.getUriForFile(context, "${context.packageName}.fileprovider", file)
}

/**
 * Image preview with camera capture button
 * Shows placeholder when no image; preview when captured
 */
@Composable
fun ImagePicker(
    imageUri: String?,
    onCaptureClick: () -> Unit
) {
    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(180.dp)
            .clip(RoundedCornerShape(12.dp))
            .background(MaterialTheme.colorScheme.surfaceVariant)
            .clickable { onCaptureClick() },
        contentAlignment = Alignment.Center
    ) {
        if (imageUri == null) {
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Icon(
                    imageVector = Icons.Default.PhotoCamera,
                    contentDescription = "Take photo",
                    tint = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f),
                    modifier = Modifier.size(48.dp)
                )
                Text(
                    text = "Tap to take photo",
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.5f),
                    fontSize = 12.sp
                )
            }
        } else {
            AsyncImage(
                model = imageUri,
                contentDescription = "Product photo",
                modifier = Modifier.fillMaxSize(),
                contentScale = ContentScale.Crop
            )
        }
    }
}


/**
 * Reusable labeled text field for product form
 * @param keyboardType Number for price/quantity, Text for name
 */
@Composable
fun ProductFormField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    placeholder: String,
    keyboardType: KeyboardType = KeyboardType.Text
) {
    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Text(
            text = label,
            fontSize = 12.sp,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)
        )
        OutlinedTextField(
            value = value,
            onValueChange = onValueChange,
            modifier = Modifier.fillMaxWidth(),
            placeholder = {
                Text(
                    placeholder,
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.3f)
                )
            },
            shape = RoundedCornerShape(8.dp),
            singleLine = true,
            keyboardOptions = KeyboardOptions(keyboardType = keyboardType),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = MaterialTheme.colorScheme.outline,
                focusedTextColor = MaterialTheme.colorScheme.onSurface,
                unfocusedTextColor = MaterialTheme.colorScheme.onSurface,
                cursorColor = MaterialTheme.colorScheme.primary
            )
        )
    }
}

/**
 * Submit button — saves product to DB via ViewModel
 */
@Composable
fun SaveButton(onClick: () -> Unit) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .clickable { onClick() },
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.primary
        )
    ) {
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .padding(16.dp),
            contentAlignment = Alignment.Center
        ) {
            Text(
                text = "Save Product",
                color = MaterialTheme.colorScheme.onPrimary,
                fontSize = 16.sp,
                fontWeight = FontWeight.Bold
            )
        }
    }
}
/**
 * Formats number with dot separator: 2000 → 2.000
 */
fun formatWithDots(input: String): String {
    val digits = input.replace(".", "").filter { it.isDigit() }
    if (digits.isEmpty()) return ""
    return digits.reversed()
        .chunked(3)
        .joinToString(".")
        .reversed()
}

/**
 * Number input field with auto-formatting and error display
 * Strips non-digits, formats with dot separator
 * Shows red error message when input is invalid
 */
@Composable
fun ProductNumberField(
    label: String,
    value: String,
    onValueChange: (String) -> Unit,
    placeholder: String,
    isError: Boolean = false,
    errorMessage: String = ""
) {
    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
        Text(
            text = label,
            fontSize = 12.sp,
            fontWeight = FontWeight.Bold,
            color = if (isError) MaterialTheme.colorScheme.error
            else MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f)
        )
        OutlinedTextField(
            value = value,
            onValueChange = { raw ->
                // Only allow digits, auto-format with dots
                val formatted = formatWithDots(raw)
                onValueChange(formatted)
            },
            modifier = Modifier.fillMaxWidth(),
            placeholder = {
                Text(
                    placeholder,
                    color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.3f)
                )
            },
            shape = RoundedCornerShape(8.dp),
            singleLine = true,
            isError = isError,
            keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = if (isError) MaterialTheme.colorScheme.error
                else MaterialTheme.colorScheme.primary,
                unfocusedBorderColor = if (isError) MaterialTheme.colorScheme.error
                else MaterialTheme.colorScheme.outline,
                focusedTextColor = MaterialTheme.colorScheme.onSurface,
                unfocusedTextColor = MaterialTheme.colorScheme.onSurface,
                cursorColor = MaterialTheme.colorScheme.primary,
                errorBorderColor = MaterialTheme.colorScheme.error
            )
        )
        // Error message
        if (isError && errorMessage.isNotBlank()) {
            Text(
                text = errorMessage,
                fontSize = 11.sp,
                color = MaterialTheme.colorScheme.error
            )
        }
    }
}
